[package]
name = "scoped_allocator"
version = "0.1.3"
authors = ["rphmeier <rphmeier@gmail.com>"]
description = "A scoped linear allocator."
license = "MIT"
repository = "https://github.com/rphmeier/scoped_allocator"
keywords = ["scoped", "linear", "allocator", "memory", "allocation"]