[package]
name = "allocators"
version = "0.1.4"
authors = ["rphmeier <rphmeier@gmail.com>"]
description = "composable memory allocators and utilities for creating more."
license = "MIT"
repository = "https://github.com/rphmeier/allocators"
keywords = ["allocator", "memory", "allocation"]